pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'echo build-stage'
                cd code/adminanddealer-backend && mvn -B -DskipTests clean package
            }
        }

        stage('Test') {
            steps {
                sh 'echo test-stage'
                cd code/adminanddealer-backend && mvn test
            }
        }
        post {
            always {
                junit 'code/adminanddealer-backend/target/surefire-reports/*.xml'
            }
        }
    }
}