pipeline {
    agent none
    
    stages {

        stage('Backend-Build') {
            agent {
                docker {
                    image 'maven:3-alpine'
                    args '-u root -v /root/.m2:/root/.m2'
                }
            }
            steps {
                sh 'echo build-stage'
                sh 'cd code/adminanddealer-backend && mvn -B -DskipTests clean package'
            }
        }

        stage("Front-Build") {
            agent {
                docker {
                    image 'node:8-alpine' 
                    args '-u root -p 3000:3000' 
                }
            }
            steps {
                sh 'echo frontend build'
                sh 'cd code/manager && npm install --unsafe-perm && npm run-script build '
            }
        }

        stage('Backend-Test') {
            agent {
                docker {
                    image 'maven:3-alpine'
                    args '-u root -v /root/.m2:/root/.m2'
                }
            }
            steps {
                sh 'echo test-stage'
                sh 'cd code/adminanddealer-backend && mvn test'
            }
        }
    }
}
